################################################################
#
# Copyright (c) 2022, liyinbin
# All rights reserved.
# Author by liyibin (jeff.li)
#
#################################################################

name: libnlp-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc =8.5 # [linux]
  - gxx =8.5 # [linux]
  - sysroot_linux-64=2.17 # [linux]
  - cmake =3.19.1
  - make
  - protobuf =3.12.4 # includes Protobuf compiler, C++ headers, Python libraries
  - zlib
  - rapidjson =1.1.0
  - pybind11 =2.8.0
  - tclap
  - gtest =1.11.0
  - gmock =1.11.0
  - benchmark